# lbconfig.yaml
apiVersion: gateway.k8s.aws/v1beta1
kind: LoadBalancerConfiguration
metadata:
  name: app-gw-lbconfig
  namespace: default
spec:
  scheme: internet-facing
  listenerConfigurations:
    - protocolPort: HTTPS:443
      defaultCertificate:arn:aws:acm:us-east-1:573469083382:certificate/f93a0602-0bff-449f-8ebd-1fc12eec10ff
 
